graphdb:
  url: http://localhost:7200/repositories/socatel-test
  username: admin
  password: root

spring.security.user:
  name: user
  password: password

management.endpoints.enabled-by-default: false
management.endpoints.web.exposure.include: health
management.endpoint.health.enabled: true

logging:
  file: socatel-graphql.log
  path: ./build/logs
