graphdb:
  url: http://localhost:7200/repositories/socatel-test
  username: admin
  password: root

es:
  portal:
    organizations:
      index: so_organisation
      name_field: organisation_name

management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health
  endpoint:
    health.enabled: true

logging:
  file: socatel-graphql.log
  path: ./build/logs
  # level.org.apache.http: DEBUG
  # level.tracer: TRACE

spring:
  security.user:
    name: user
    password: password
  elasticsearch:
    jest:
      uris: http://localhost:7200
      username: user
      password: password
